M48
; DRILL file KiCad 10.0.4 date 2026-07-10T07:10:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-10T07:10:49-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X26.875Y-10.16
X31.875Y-5.16
X31.875Y-15.16
X34.375Y-5.16
X34.375Y-15.16
T2
X2.5Y-2.5
X2.5Y-17.82
M30
